language: cpp

sudo: false

addons:
  apt:
    packages:
      - gcc-5
      - g++-5
      - cmake

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5


before_script:
  - export CXX=$COMPILER
  - cd cpp/MPMCQueue
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. 

script: make && ctest
